#screen_0 = /home/lucas/.config/hypr/backgrounds/ender_dragon.png
#screen_1 = /home/lucas/.config/hypr/backgrounds/yoda.jpg
#screen_2 = /home/lucas/.config/hypr/backgrounds/gandalf.jpg
#screen_3 = /home/lucas/.config/hypr/backgrounds/doe.jpg
#screen_4 = /home/lucas/.config/hypr/backgrounds/link.png
#screen_5 = /home/lucas/.config/hypr/backgrounds/dune.jpg
#screen_6 = /home/lucas/.config/hypr/backgrounds/heimerdinger.jpg
#screen_7 = /home/lucas/.config/hypr/backgrounds/hollow_knight.jpg
#screen_8 = /home/lucas/.config/hypr/backgrounds/cites_or.jpg
#screen_9 = /home/lucas/.config/hypr/backgrounds/joker.jpg

#eDP-1-0 = /home/lucas/.config/hypr/backgrounds/ender_dragon.png

#preload = /home/lucas/.config/hypr/backgrounds/ender_dragon.png
#wallpaper = eDP-1, /home/lucas/.config/hypr/backgrounds/ender_dragon.png

splash=false

wallpaper {
		monitor = eDP-1
		path = /home/lucas/.config/hypr/backgrounds/ender_dragon.png
		fit_mode = cover
}
